import "../src/index.scss"

export const Paragraph = () => <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nam, neque perspiciatis fugiat repellat eaque natus inventore. Expedita, autem tenetur minima enim doloremque sed? Voluptates natus iste iure quam id esse error maxime, vitae quos? Eos facere, fuga magni officia incidunt atque alias quos dolorum asperiores sapiente animi quisquam eius!</p>

export const MultipleParagraphs = () => <>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla nihil aspernatur sed optio minus consequuntur cumque voluptatibus odit deleniti autem earum praesentium nam ipsum sint eligendi numquam eius recusandae quod neque, asperiores impedit architecto quos doloribus? Atque numquam eveniet illum ducimus exercitationem quibusdam natus voluptatem soluta, aliquid est recusandae, dolorem minima aspernatur magnam provident iure nihil voluptas. Ipsa, magni cupiditate!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A tempore vero laborum eum rem expedita minus, quaerat veritatis eveniet nisi odio suscipit laboriosam ut nemo eaque rerum animi pariatur consequatur maiores asperiores accusamus! Voluptate illum sequi quibusdam, est non, ab quo quia accusantium facere illo veniam in! Excepturi quos perspiciatis sit sequi. Voluptatem, magni? Atque dolorem nobis nisi! Optio voluptates officia commodi temporibus laudantium, dolorum harum quidem enim unde distinctio aliquam labore aut repellendus illo ex quas natus expedita alias quod provident doloremque amet deserunt. Ad sint ex nostrum tempora quae quod, esse nobis cum commodi expedita. Mollitia, non voluptatem?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, repellat eos. Nisi laudantium natus dicta reiciendis excepturi in nihil inventore ducimus, nostrum atque dolore maxime explicabo voluptatum temporibus accusantium asperiores commodi aut, quos veniam omnis quasi blanditiis? Rem, rerum possimus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quod optio aspernatur natus! Id placeat architecto quibusdam laborum, perspiciatis, nulla deserunt reprehenderit consectetur quae dolores quisquam temporibus harum nostrum non eum adipisci error reiciendis provident quasi maiores quas ea doloremque? Ducimus ex porro totam consequuntur veniam harum at rem nostrum vitae asperiores adipisci ullam repellat iste et labore, error obcaecati voluptatum mollitia quia. Doloribus tenetur veritatis sunt tempora vitae cum.</p>
</>
